# Generated by Django 5.0.4 on 2024-04-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexerciseset',
            name='set',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.set'),
            preserve_default=False,
        ),
    ]
